### ISSUE TITLE
The Account Details

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-wallet#100]
**Describe the bug**
The wallet does not show the account details:
- Balance
- Staked POKT
- Staking Status
- Account Type
- Last TX

**To Reproduce**
1. Go to import
2. Import a Staked App or node account
3. Go to Account details
4. See errors:
- Balance 0.00 POKT  in consequence $ 0.00 USD
- Staked POKT : 0
- Staking Status: UNSTAKED
- Account Type: NA
- Last TX: No tx

**Screenshots**
The account on the Dashboard
<img width="1242" alt="Screen Shot 2020-10-19 at 6 57 35 PM" src="https://user-images.githubusercontent.com/67430643/96525361-4f258d00-1240-11eb-9462-9380fd7ed0af.png">
The Account on the Wallet
<img width="860" alt="Screen Shot 2020-10-19 at 6 54 37 PM" src="https://user-images.githubusercontent.com/67430643/96525382-606e9980-1240-11eb-8ba3-6ee84d465322.png">

**Expected behavior**
The account information should match the info from the network

**Comment by pabelnl** [comment]
This issue was addressed in PR: 
[https://github.com/pokt-network/pocket-wallet/pull/105](PR-105)
