### ISSUE TITLE
USD getting rounded up.

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-wallet#125]
**Describe the bug**
When in the wallet (https://wallet.pokt.network/send), it has been noticed that we are rounding up the USD related to the POKT.

**To Reproduce**

Please find the video here @pabelnl 
https://www.loom.com/share/6d67f93439e8421fb11aaf0b942bc409

1. Go go the wallet.
2. Create or import an account.
3. Go to "send", as if you were going to send a TX.
4. Write 100 in the USD field.
5. Start using the arrows in the POKT field, going down.

**Expected behavior**
The USD values must change in relation to the POKT being varied.

**Screenshots**
![image](https://user-images.githubusercontent.com/17748171/99552787-2c4fdb00-299c-11eb-9ae3-55fa53d8d847.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome

**Comment by pabelnl** [comment]
If you use the POKT arrows and reduce the amount by 0.01 at a time the USD value will change when the POKT is enough for the conversion to change in USD. Please share more information about the issue with exact values and the expected result. 

@emedrano2112
