### ISSUE TITLE
KeyFile import is broken

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-wallet#131]
**Describe the bug**
When the user provides its keyfile.json to try to import it to the wallet, after entering the passphrase the APP shows an "incorrect file" message.

Notice that the keyfile was the same one exported when account was created in the wallet.

At the moment, the user is only able to import by using the privateKey file.

**To Reproduce**
1. Go to https://wallet.pokt.network/import
2. Click on "upload keyfile" and select a valid keyfile.json
3. Click on import.
4. Find the "incorrect file" message.

**Expected behavior**
The APP should recognize the file and allow the user to import its account to the walled with the keyfile.json

**Screenshots**
![Screen Shot 2021-01-25 at 11 23 44](https://user-images.githubusercontent.com/17748171/105719356-f6315900-5f00-11eb-99ad-3bdf849aca8a.png)

**Comment by pabelnl** [comment]
Not an issue, create/import works fine, the issue is related to a wrong message for the user when the passphrase is wrong in a x scenario.
