### ISSUE TITLE
[BUG REPORT] No transaction hash displayed after completing transaction

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-wallet#156]
User (Patrick) reports that with the staging version using Gateway for data, he did not receive a transaction hash after completing the transaction.

Patrick727 — Today at 6:48 PM
I sent 100 pokt but got now proof

Alex F | NachoNodes — Today at 6:48 PM
does it normally give you proof on prod

Patrick727 — Today at 6:48 PM
went right back to welcome
yeah it will normally send me the hash

**Comment by nymd** [comment]
The txn did go through successfully.

**Comment by derrandz** [comment]
After testing out in the testnet version, I was able to successfully send a transaction (_the transaction showed up, tx: 5A1033245506F784B2B892D2F1B451584753482BFA0BA9DE86EBF4A265A1EABD_) however the described behavior is accurate, once the send is done you are redirected to the welcome page.

After digging a bit, it seems that this is caused primarily by new response format from the `getTx` datasource function. i.e: the wallet was expecting `response.transaction.txResult` where we are now receiving `response.tx_result`.

**Comment by derrandz** [comment]
Also this is related to the transaction details page not receiving the txHash param properly.

**Comment by derrandz** [comment]
Fixed by #158
