### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-wallet#47]
Wallet Testnet:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-170464047-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-170464047-1');
</script>

**Comment by pabelnl** [comment]
Should this be added in each view or in the header?
